parameters:
#    tomi_s_test.example.class: TomiS\TestBundle\Example

services:
#    tomi_s_test.example:
#        class: %tomi_s_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
